name: projeto_alex_flutter
description: Sistema de Monitoramento ESP32 - Versão Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI e Componentes
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  lottie: ^2.7.0
  
  # Estado e Gerenciamento
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  
  # HTTP e API
  http: ^1.1.0
  dio: ^5.3.2
  
  # Armazenamento Local
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Utilitários
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  
  # Gráficos e Visualização
  fl_chart: ^0.65.0
  
  # Notificações
  flutter_local_notifications: ^16.3.0
  
  # Permissões
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 